# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0nACQ450PXR2_1tLHOX9Pfxwv2ceA21
"""
import streamlit as st



st.title("Addition of two given numbers")

num1 = st.number_input('Insert number 1')
#st.write('The first number is ', num1)

num2 = st.number_input('Insert number 2')
#st.write('The second number is ', num2)

sum = num1 + num2
st.write("**Addition of two numbers is**", sum)